baseURL = "/"
languageCode = "en-us"
title = "Hawley Farm"
[[menu.main]]
name = "March 2019"
parent = "Blog"
url = "/blog/blog2"
weight = 2
[[menu.main]]
name = "February 2019"
parent = "Blog"
url = "/blog/blog1"
weight = 1
[[menu.main]]
name = "Reviews"
parent = "Reviews/More information"
url = "/reviews/guestbook/"
weight = 5
[[menu.main]]
name = "Contact Us"
parent = "Reviews/More information"
url = "/contact"
weight = 4
[[menu.main]]
name = "Stables"
parent = "Accommodation"
url = "/accommodation/stables"
weight = 3
[[menu.main]]
name = "How to find us"
parent = "Reviews/More information"
url = "/info/findus"
weight = 3
[[menu.main]]
name = "Wagonhouse"
parent = "Accommodation"
url = "/accommodation/wagonhouse"
weight = 2
[[menu.main]]
name = "When and where"
parent = "Reviews/More information"
url = "/info/whenandwhere"
weight = 2
[[menu.main]]
name = "Caravaning and camping"
parent = "Reviews/More information"
url = "/info/camping"
weight = 1
[[menu.main]]
name = "Ciderpress"
parent = "Accommodation"
url = "/accommodation/ciderpress"
weight = 1
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "booking"
name = "Availability and Booking"
url = "/booking/"
weight = 4
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
name = "Reviews/More information"
url = "#"
weight = 5
[[menu.main]]
name = "Accommodation"
url = "#"
weight = 2
[params]
containerMaxWidth = "700px"
dateFormat = "Jan 2, 2006"
hideFooter = false
includeBootstrapJs = false
showActiveNav = true
[permalinks]
post = "/:filename/"
[taxonomies]
tag = "tags"
